### PR TITLE
Support Flask 3.0

### LINKED ISSUE #28: Fails to import with werkzeug 3.0
This is a heads-up that [werkzeug 3.0](https://werkzeug.palletsprojects.com/en/3.0.x/changes/#version-3-0-0) was released a few hours ago and httpbin fails on import.

Looks like the relevant change is in here: https://github.com/pallets/werkzeug/pull/2619

```python
httpbin> Traceback (most recent call last):
httpbin>   File "<string>", line 1, in <module>
httpbin>   File "<string>", line 1, in <lambda>
httpbin>   File "/nix/store/mlzs555x59i8vk160d2yr683mwcacscc-python3-3.11.5/lib/python3.11/importlib/__init__.py", line 126, in import_module
httpbin>     return _bootstrap._gcd_import(name[level:], package, level)
httpbin>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
httpbin>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
httpbin>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
httpbin>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
httpbin>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
httpbin>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
httpbin>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
httpbin>   File "/nix/store/wckwd80x7b1fnpkyngcf45rq4lz997w4-python3.11-httpbin-0.10.1/lib/python3.11/site-packages/httpbin/__init__.py", line 3, in <module>
httpbin>     from .core import *
httpbin>   File "/nix/store/wckwd80x7b1fnpkyngcf45rq4lz997w4-python3.11-httpbin-0.10.1/lib/python3.11/site-packages/httpbin/core.py", line 35, in <module>
httpbin>     from werkzeug.http import parse_authorization_header
httpbin> ImportError: cannot import name 'parse_authorization_header' from 'werkzeug.http' (/nix/store/mg6vcsnplj56nyjlzzjph2wxrsc9449n-python3.11-werkzeug-3.0.0/lib/python3.11/site-packages/werkzeug/http.py)
```

### PR DESCRIPTION
**Pull request by nateprewitt**
This PR should get httpbin working with Flask 3.0. The other recent changes to get Flask 2.0 working in `main` already broke Flask<2.2.4 so I've updated the dependencies to correctly reflect what we're compatible with. This should also resolve #28.

This PR changes three primary pieces:

1. Move to using the WWWAuthenticate constructor that was introduced in werkzeug 2.0 and became the only supported interface in werkzeug 3.0.
2. Move to `Authorization.from_header` which was introduced in werkzeug 2.3 and is the only supported interface in werkzeug 3.0. `parse_authorization_header` was already [an alias](https://github.com/pallets/werkzeug/blob/f2e0ac6e915285cd39d72ae9e83eec5159d989cd/src/werkzeug/http.py#L814-L836) for this in versions of werkzeug we support.
3. We were doing some unneeded byte conversion for the Location header on redirect. This was a legacy change from 10 years ago to accommodate werkzeug casting all headers to `str` so we ensured they were `utf-8` bytes. werkzeug stopped this conversion in 3.0 and we already have a Python 3 `utf-8` string as input. We should be able drop this safely with our support range.

### CODE REVIEW

**Review by jeffvanvoorst — APPROVED** [review]
Looks like a good fix.  I wasn't aware of the details for .helpers.

File: httpbin/core.py [hunk 1]
```diff
@@ -636,16 +637,13 @@ def redirect_to():
...
-    # We need to build the response manually and convert to UTF-8 to prevent
-    # werkzeug from "fixing" the URL. This endpoint should set the Location
-    # header to the exact string supplied.
     response = app.make_response("")
     response.status_code = 302
     if "status_code" in args:
         status_code = int(args["status_code"])
         if status_code >= 300 and status_code < 400:
             response.status_code = status_code
-    response.headers["Location"] = args["url"].encode("utf-8")
```
Comment (jeffvanvoorst) [inline httpbin/core.py:648]: Was this issue resolved in a later version of werkzeug?  I am curious to understand why it is no longer necessary.

Comment (nateprewitt) [reply httpbin/core.py:648]: I think that's covered in item 3 in the PR overview. Was there something more specific you were wondering about?

Comment (jeffvanvoorst) [reply httpbin/core.py:648]: No, thanks for pointing that out.

**Review by sigmavirus24 — APPROVED** [review]
