### ISSUE TITLE
Release a new version on Pypi with werkzeug 3 support

### ISSUE THREAD

**Issue by honglei** [psf/httpbin#35]
httpbin depends werkzeug which will  werkzeug3.0, but `parse_authorization_header` has been removed from werkzeug.
So, we need a new release to make `import httpbin` corrent.
```
PS E:\PythonPrj\6xx\crud_test> python.exe -m pip install -U httpbin --proxy http://localhost:6666
Collecting httpbin
  Using cached httpbin-0.10.1-py2.py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: Flask in c:\python312\lib\site-packages (from httpbin) (3.0.0)
Requirement already satisfied: brotlicffi in c:\python312\lib\site-packages (from httpbin) (1.1.0.0)
Requirement already satisfied: decorator in c:\python312\lib\site-packages (from httpbin) (5.1.1)
Requirement already satisfied: flasgger in c:\python312\lib\site-packages (from httpbin) (0.9.7.1)
Requirement already satisfied: werkzeug>=0.14.1 in c:\python312\lib\site-packages (from httpbin) (3.0.0)
Requirement already satisfied: six in c:\python312\lib\site-packages (from httpbin) (1.16.0)
Requirement already satisfied: greenlet>=3.0.0a1 in c:\python312\lib\site-packages (from httpbin) (3.0.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\python312\lib\site-packages (from werkzeug>=0.14.1->httpbin) (2.1.3)
Requirement already satisfied: cffi>=1.0.0 in c:\python312\lib\site-packages (from brotlicffi->httpbin) (1.16.0)
Requirement already satisfied: PyYAML>=3.0 in c:\python312\lib\site-packages (from flasgger->httpbin) (6.0.1)
Requirement already satisfied: jsonschema>=3.0.1 in c:\python312\lib\site-packages (from flasgger->httpbin) (4.19.1)
Requirement already satisfied: mistune in c:\python312\lib\site-packages (from flasgger->httpbin) (3.0.2)
Requirement already satisfied: packaging in c:\python312\lib\site-packages (from flasgger->httpbin) (23.2)
Requirement already satisfied: Jinja2>=3.1.2 in c:\python312\lib\site-packages (from Flask->httpbin) (3.1.2)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\python312\lib\site-packages (from Flask->httpbin) (2.1.2)
Requirement already satisfied: click>=8.1.3 in c:\python312\lib\site-packages (from Flask->httpbin) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in c:\python312\lib\site-packages (from Flask->httpbin) (1.6.3)
Requirement already satisfied: pycparser in c:\python312\lib\site-packages (from cffi>=1.0.0->brotlicffi->httpbin) (2.21)
Requirement already satisfied: colorama in c:\python312\lib\site-packages (from click>=8.1.3->Flask->httpbin) (0.4.6)
Requirement already satisfied: attrs>=22.2.0 in c:\python312\lib\site-packages (from jsonschema>=3.0.1->flasgger->httpbin) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\python312\lib\site-packages (from jsonschema>=3.0.1->flasgger->httpbin) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\python312\lib\site-packages (from jsonschema>=3.0.1->flasgger->httpbin) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\python312\lib\site-packages (from jsonschema>=3.0.1->flasgger->httpbin) (0.10.6)
Using cached httpbin-0.10.1-py2.py3-none-any.whl (100 kB)
Installing collected packages: httpbin
Successfully installed httpbin-0.10.1
```

Error:
```
File "e:\xx\libs\aioquic-main\examples\http3_server.py", line 560, in <module>
  module = importlib.import_module(module_str)
File "e:\xx\libs\aioquic-main\examples\demo.py", line 9, in <module>
  import httpbin
File "c:\python312\lib\site-packages\httpbin\__init__.py", line 3, in <module>
  from .core import *
File "c:\python312\lib\site-packages\httpbin\core.py", line 35, in <module>
  from werkzeug.http import parse_authorization_header

builtins.ImportError: cannot import name 'parse_authorization_header' from 'werkzeug.http' (c:\Python312\Lib\site-packages\werkzeug\http.py)
```

**Comment by hartwork** [comment]
@honglei could you adjust the title also saying "with werkzeug 3 support" or similar?

Related:
- #29 (fixing pull request)
- #36 (duplicate)

**Comment by frantisekz** [comment]
@hartwork For the 0.10.2, merging at least #34 would seem necessary (and #32 too, so httpbin is more "lightweight"?)?

**Comment by hartwork** [comment]
@frantisekz I'm not the one to decide, but they don't look like release blockers from a quick look. Would be great if these could receive review before or after a next release.

**Comment by frantisekz** [comment]
> @frantisekz I'm not the one to decide, but they don't look like release blockers from a quick look. Would be great if these could receive review before or after a next release.

The first one is for Flask 3 support, Flask goes in together with Werkzeug (about which is this issue).

**Comment by AdamWill** [comment]
right, #34 is needed for flask 2.3.0 and higher.

**Comment by Safihre** [comment]
Could someone please make a new release so we can all get our environments back up to date? :)

**Comment by AdamWill** [comment]
The release did not include #34 , so it still does not work with flask 2.3.0 or higher.

**Comment by AdamWill** [comment]
It also did not include #41 , so it does not work with recent werkzeug.

**Comment by Safihre** [comment]
Yeah I also realized that later 🥲
